name: Comment on PR with GitHub CLI

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Login GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Post a comment to the PR
        run: gh pr comment "${{ github.event.pull_request.number }}" --body "Thank you for your pull request! We will review it as soon as possible."
