name: Build App windows

on:
  workflow_dispatch: { }
defaults:
  run:
    shell: bash

jobs:
  buildForWindowsBasedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: [ self-hosted, Windows ]
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
        buildMethod:
          - BuildApp.Build
        unityPath:
          - '"C:\Program Files\Unity\Hub\Editor\2022.3.43f1\Editor\Unity.exe"' #使用しているUnityのバージョンのパス
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          clean: false
          submodules: recursive

      - name: Run Build
        run: echo Hello
