name: Build App windows

on:
  workflow_dispatch: { }
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: [ self-hosted, Windows ]
    steps:
      - uses: actions/checkout@v4
        name: Run Build
        run: echo Hello
