name: Tst

on:
  workflow_dispatch: { }
defaults:
  run:
    shell: pwsh

jobs:
  buildForWindowsBasedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: [ self-hosted, Windows ]
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          clean: false
          submodules: recursive
  
      - name: Run Build
        run: |
          & "C:\Program Files\Unity\Hub\Editor\2022.3.43f1\Editor\Unity.exe" -batchmode -quit -projectPath "C:\Users\nsakuma\Desktop\Projects\AssetRegulation" -executeMethod BuildApp.Build
